russian_a1_possible_questions = [
    "Привет!",
    "Как Дела?",
    "Я Тим.",
    "Как тебя зовут?",
    "Мне 20 лет.",
    "Где ты живешь?",
    "Я люблю пиццу.",
    "Ты говоришь по-английски?",
    "Что это?",
    "Какой у тебя любимый цвет?",
    "Мне нравится музыка.",
    "Ты студент?",
    "Это моя книга.",
    "Какой сегодня день?",
    "Сколько это стоит?",
    "Ты откуда?",
    "Я работаю в офисе.",
    "У тебя есть домашнее животное?",
    "Какой твой любимый фильм?",
    "Ты занимаешься спортом?",
    "Мне нужна помощь.",
    "Какой у тебя номер телефона?",
    "Где туалет?",
    "Что ты делаешь сегодня?",
    "Это хорошо.",
    "Мне не нравится дождь.",
    "Какой у тебя день рождения?",
    "Ты любишь путешествовать?",
    "Это очень интересно.",
    "Какой твой любимый напиток?",
    "У меня есть брат.",
    "Мне нравится читать.",
    "Ты знаешь русский?",
    "Это твоя работа?",
    "Сколько тебе лет?",
    "Ты пойдешь на вечеринку?",
    "Какой у тебя адрес?",
    "Ты понимаешь меня?",
    "Это твой друг?",
    "Как ты себя чувствуешь?",
    "Ты любишь кошек?",
    "Где ты учишься?",
    "Что ты хочешь поесть?",
    "Какой у тебя хобби?",
    "Мне нужно время.",
    "Ты любишь зиму?",
    "Это хороший день.",
    "Какой у тебя любимый журнал?",
    "Ты видел этот фильм?",
    "Как долго ты здесь?",
    "Ты любишь кофе?",
    "Что ты делаешь на выходных?",
    "Какой у тебя любимый спорт?",
    "Ты любишь гулять?",
    "Какую музыку ты слушаешь?",
    "Какой твой любимый ресторан?",
    "Что ты предпочитаешь, чай или кофе?",
    "Это моя семья.",
    "Ты хочешь поехать в Россию?",
    "Какой у тебя любимый праздник?",
    "Ты умеешь готовить?",
    "Какой у тебя стиль одежды?",
    "Это твое имя?",
    "Какой твой любимый клуб?",
    "Ты любишь рисовать?",
    "Это моя машина.",
    "Какой у тебя любимый сайт?",
    "Ты смотрел новости?",
    "Какой у тебя любимый сезон?",
    "Ты знаешь кого-нибудь в России?",
    "Как ты провел выходные?",
    "Ты любишь природу?",
    "Это твоя работа?",
    "Какой твой любимый композитор?",
    "Ты умеешь играть на музыкальном инструменте?",
    "Какой у тебя любимый актер?",
    "Ты поедешь на море?",
    "Какой у тебя любимый вид спорта?",
    "Ты любишь читать книги?",
    "Это мой лучший друг.",
    "Какой у тебя любимый сайт?",
    "Ты видел этот спектакль?",
    "Как ты любишь отдыхать?",
    "Какой у тебя любимый цвет?",
    "Ты знаешь, где я могу купить это?",
    "Какой у тебя любимый вид искусства?",
    "Ты часто путешествуешь?",
    "Какой у тебя любимый музыкальный жанр?",
    "Ты учишься в университете?",
    "Какой у тебя любимый магазин?",
    "Ты ходишь в спортзал?",
    "Какой твой любимый предмет в школе?",
    "Ты любишь готовить?",
    "Это твой стол?",
    "Как ты себя называешь?",
    "Какой у тебя любимый актёр?",
    "Ты смотришь фильмы?",
    "Какой у тебя любимый пейзаж?",
    "Ты занимаешься йогой?",
    "Как ты относишься к спорту?",
    "Какой твой любимый праздник?",
    "Ты читаешь газеты?",
    "Это твое фото?",
    "Какой твой любимый сериал?",
    "Ты работаешь или учишься?",
    "Какой у тебя любимый десерт?",
    "Ты слышал эту песню?",
    "Какой у тебя любимый вид спорта?",
    "Ты любишь посещать музеи?",
    "Как ты проводишь свободное время?",
    "Это твоя любимая игра?",
    "Какой у тебя любимый цвет?",
    "Ты любишь рисовать?",
    "Какой у тебя любимый композитор?",
    "Ты видишь это?",
]

russian_a1_possible_answers = [
    "hello",
    "how are you",
    "i am tim",
    "what is your name",
    "i am 20 years old",
    "where do you live",
    "i love pizza",
    "do you speak english",
    "what is this",
    "what is your favorite color",
    "i like music",
    "are you a student",
    "this is my book",
    "what day is today",
    "how much does this cost",
    "where are you from",
    "i work in an office",
    "do you have a pet",
    "what is your favorite movie",
    "do you play sports",
    "i need help",
    "what is your phone number",
    "where is the bathroom",
    "what are you doing today",
    "this is good",
    "i don't like rain",
    "when is your birthday",
    "do you like to travel",
    "this is very interesting",
    "what is your favorite drink",
    "i have a brother",
    "i like to read",
    "do you know russian",
    "is this your job",
    "how old are you",
    "are you going to the party",
    "what is your address",
    "do you understand me",
    "is this your friend",
    "how do you feel",
    "do you like cats",
    "where do you study",
    "what do you want to eat",
    "what is your hobby",
    "i need time",
    "do you like winter",
    "this is a good day",
    "what is your favorite magazine",
    "have you seen this movie",
    "how long have you been here",
    "do you like coffee",
    "what do you do on weekends",
    "what is your favorite sport",
    "do you like to walk",
    "what kind of music do you listen to",
    "what is your favorite restaurant",
    "do you prefer tea or coffee",
    "this is my family",
    "do you want to go to russia",
    "what is your favorite holiday",
    "can you cook",
    "what is your style of clothing",
    "is this your name",
    "what is your favorite club",
    "do you like to draw",
    "this is my car",
    "what is your favorite website",
    "have you watched the news",
    "what is your favorite season",
    "do you know anyone in russia",
    "how did you spend the weekend",
    "do you love nature",
    "is this your job",
    "who is your favorite composer",
    "can you play a musical instrument",
    "who is your favorite actor",
    "are you going to the sea",
    "what is your favorite type of sport",
    "do you love to read books",
    "this is my best friend",
    "what is your favorite website",
    "did you see this play",
    "how do you like to relax",
    "what is your favorite color",
    "do you know where I can buy this",
    "what is your favorite type of art",
    "do you travel often",
    "what is your favorite music genre",
    "are you studying at the university",
    "what is your favorite store",
    "do you go to the gym",
    "what is your favorite subject in school",
    "do you like to cook",
    "is this your desk",
    "what do you call yourself",
    "who is your favorite actor",
    "do you watch movies",
    "what is your favorite landscape",
    "do you do yoga",
    "how do you feel about sports",
    "what is your favorite holiday",
    "do you read newspapers",
    "is this your photo",
    "what is your favorite series",
    "do you work or study",
    "what is your favorite dessert",
    "have you heard this song",
    "what is your favorite type of sport",
    "do you like to visit museums",
    "how do you spend your free time",
    "is this your favorite game",
    "what is your favorite color",
    "do you like to draw",
    "who is your favorite composer",
    "do you see this",
]

russian_a2_possible_questions = [
    "Как прошел твой день?",
    "Что ты обычно делаешь на выходных?",
    "Ты часто ходишь в кино?",
    "Какой твой любимый фильм?",
    "Что ты будешь делать завтра?",
    "Ты любишь читать книги?",
    "Какая у тебя любимая книга?",
    "Ты говоришь на других языках?",
    "Где ты работаешь?",
    "Какой у тебя опыт работы?",
    "Ты любишь готовить?",
    "Какое твое любимое блюдо?",
    "Ты когда-нибудь был за границей?",
    "Какой самый интересный город ты посетил?",
    "Что ты думаешь о русском языке?",
    "Ты слушаешь музыку?",
    "Какая музыка тебе нравится?",
    "Какой у тебя хобби?",
    "Ты занимаешься спортом?",
    "Какой твой любимый вид спорта?",
    "Ты любишь путешествовать?",
    "Где ты хотел бы побывать?",
    "Какой у тебя день рождения?",
    "Ты празднуешь Новый год?",
    "Что ты обычно готовишь на праздник?",
    "Ты умеешь кататься на велосипеде?",
    "Что ты предпочитаешь: горы или море?",
    "Какой у тебя любимый напиток?",
    "Ты пьешь кофе или чай?",
    "Как часто ты ешь в ресторанах?",
    "Ты когда-нибудь играл в настольные игры?",
    "Какой твой любимый настольный игра?",
    "Ты любишь животных?",
    "Какой у тебя домашний питомец?",
    "Ты когда-нибудь принимал участие в волонтерстве?",
    "Какой у тебя самый запоминающийся момент в жизни?",
    "Ты предпочитаешь вечеринки или тихие вечера?",
    "Как ты обычно проводишь время с друзьями?",
    "Что тебе нравится делать в свободное время?",
    "Ты любишь осень?",
    "Какой твой любимый сезон?",
    "Ты слушал русскую музыку?",
    "Какой у тебя любимый российский артист?",
    "Ты смотрел российские сериалы?",
    "Какой твой любимый сериал?",
    "Ты предпочитаешь готовую еду или домашнюю?",
    "Ты когда-нибудь учил других?",
    "Какой самый сложный предмет в школе?",
    "Ты любишь рисовать?",
    "Какой твой любимый художник?",
    "Ты когда-нибудь писал стихи?",
    "Что тебя вдохновляет?",
    "Какой у тебя любимый праздник?",
    "Ты любишь сюрпризы?",
    "Какой сюрприз тебе запомнился?",
    "Ты умеешь играть на музыкальном инструменте?",
    "Какой инструмент ты играешь?",
    "Ты когда-нибудь участвовал в театре?",
    "Что ты думаешь о театре?",
    "Какой у тебя любимый спектакль?",
    "Ты умеешь танцевать?",
    "Какой стиль танца тебе нравится?",
    "Ты когда-нибудь ходил на мастер-классы?",
    "Какой мастер-класс ты бы хотел посетить?",
    "Ты любишь прогулки на свежем воздухе?",
    "Где ты любишь гулять?",
    "Какой у тебя любимый парк?",
    "Ты любишь смотреть фильмы в оригинале?",
    "Какой фильм ты недавно смотрел?",
    "Что ты обычно ешь на завтрак?",
    "Как ты относишься к здоровому питанию?",
    "Ты когда-нибудь пробовал вегетарианство?",
    "Какой твой любимый вид чая?",
    "Ты часто ходишь на выставки?",
    "Какой выставке ты был недавно?",
    "Ты любишь участвовать в конкурсах?",
    "Какой конкурс был самым интересным?",
    "Ты когда-нибудь встречал знаменитостей?",
    "Кто из знаменитостей тебе нравится?",
    "Ты предпочитаешь фильмы или книги?",
    "Какой жанр тебе больше нравится?",
    "Ты когда-нибудь был на концерте?",
    "Какой концерт был самым запоминающимся?",
    "Ты знаешь какие-нибудь народные традиции?",
    "Какой праздник ты любишь больше всего?",
    "Ты знаешь какие-нибудь русские пословицы?",
    "Какой урок ты вынес из своей жизни?",
    "Ты веришь в судьбу?",
    "Как ты относишься к случайностям?",
    "Ты любишь планировать свои дела?",
    "Как ты организуешь свое время?",
    "Ты умеешь вести бюджет?",
    "Как ты экономишь деньги?",
    "Ты когда-нибудь мечтал о своей мечте?",
    "Что для тебя важно в жизни?",
    "Ты когда-нибудь задумывался о будущем?",
    "Как ты видишь свою жизнь через пять лет?",
    "Ты любишь мечтать?",
    "Какой твой самый заветный сон?",
]

russian_a2_possible_answers = [
    "how was your day",
    "what do you usually do on weekends",
    "do you often go to the movies",
    "what is your favorite movie",
    "what will you do tomorrow",
    "do you like reading books",
    "what is your favorite book",
    "do you speak other languages",
    "where do you work",
    "what is your work experience",
    "do you like cooking",
    "what is your favorite dish",
    "have you ever been abroad",
    "what is the most interesting city you visited",
    "what do you think about the russian language",
    "do you listen to music",
    "what music do you like",
    "what is your hobby",
    "do you play sports",
    "what is your favorite sport",
    "do you like to travel",
    "where would you like to go",
    "when is your birthday",
    "do you celebrate new year",
    "what do you usually cook for holidays",
    "can you ride a bike",
    "do you prefer mountains or the sea",
    "what is your favorite drink",
    "do you drink coffee or tea",
    "how often do you eat at restaurants",
    "have you ever played board games",
    "what is your favorite board game",
    "do you like animals",
    "do you have a pet",
    "have you ever participated in volunteering",
    "what is your most memorable moment in life",
    "do you prefer parties or quiet evenings",
    "how do you usually spend time with friends",
    "what do you like to do in your free time",
    "do you like autumn",
    "what is your favorite season",
    "have you listened to russian music",
    "who is your favorite russian artist",
    "have you watched russian series",
    "what is your favorite series",
    "do you prefer ready-made food or home-cooked",
    "have you ever taught someone",
    "what is the hardest subject in school",
    "do you like drawing",
    "who is your favorite artist",
    "have you ever written poetry",
    "what inspires you",
    "what is your favorite holiday",
    "do you like surprises",
    "what surprise do you remember",
    "can you play a musical instrument",
    "which instrument do you play",
    "have you ever participated in theater",
    "what do you think about theater",
    "what is your favorite play",
    "can you dance",
    "what style of dance do you like",
    "have you ever attended workshops",
    "which workshop would you like to attend",
    "do you enjoy walks in fresh air",
    "where do you like to walk",
    "what is your favorite park",
    "do you like to watch movies in original language",
    "what movie did you watch recently",
    "what do you usually eat for breakfast",
    "how do you feel about healthy eating",
    "have you ever tried vegetarianism",
    "what is your favorite type of tea",
    "do you often go to exhibitions",
    "which exhibition did you visit recently",
    "do you like to participate in contests",
    "what contest was the most interesting",
    "have you ever met celebrities",
    "who is your favorite celebrity",
    "do you prefer movies or books",
    "what genre do you like more",
    "have you ever been to a concert",
    "what concert was the most memorable",
    "do you know any folk traditions",
    "which holiday do you love the most",
    "do you know any russian proverbs",
    "what lesson have you learned from your life",
    "do you believe in fate",
    "how do you feel about coincidences",
    "do you like to plan your affairs",
    "how do you organize your time",
    "can you manage a budget",
    "how do you save money",
    "have you ever dreamed of your dream",
    "what is important to you in life",
    "have you ever thought about the future",
    "how do you see your life in five years",
    "do you like to dream",
    "what is your most cherished dream",
]


russian_b1_possible_questions = [
    "Что ты думаешь о своей работе?",
    "Как ты проводишь отпуск?",
    "Ты предпочитаешь отдых на пляже или в горах?",
    "Какое место в мире ты мечтаешь посетить?",
    "Ты когда-нибудь пробовал заниматься йогой?",
    "Какой у тебя самый любимый момент из детства?",
    "Что ты думаешь о современных технологиях?",
    "Как часто ты используешь интернет?",
    "Ты любишь проводить время на природе?",
    "Что для тебя значит семья?",
    "Ты умеешь делать что-то своими руками?",
    "Как ты поддерживаешь свою физическую форму?",
    "Ты когда-нибудь участвовал в соревнованиях?",
    "Как ты относишься к спорту как к образу жизни?",
    "Ты когда-нибудь учился играть на музыкальном инструменте?",
    "Какой твой любимый стиль музыки?",
    "Что для тебя важнее: работа или личная жизнь?",
    "Ты предпочитаешь работать в команде или самостоятельно?",
    "Как ты относишься к критике?",
    "Что ты думаешь о саморазвитии?",
    "Как ты ставишь цели на будущее?",
    "Ты когда-нибудь мечтал стать знаменитым?",
    "Какой самый важный урок ты усвоил в жизни?",
    "Ты веришь в дружбу между мужчиной и женщиной?",
    "Что ты думаешь о любви?",
    "Как ты относишься к долгосрочным отношениям?",
    "Ты любишь готовить для своих друзей?",
    "Какой у тебя самый необычный опыт в жизни?",
    "Ты когда-нибудь сталкивался с трудностями в жизни?",
    "Что ты делаешь, чтобы справиться со стрессом?",
    "Ты когда-нибудь думал о смене профессии?",
    "Как ты считаешь, важна ли работа для счастья?",
    "Ты часто общаешься с родителями?",
    "Как ты проводишь время с друзьями?",
    "Что ты делаешь, когда тебе грустно?",
    "Как ты поднимаешь себе настроение?",
    "Ты любишь смотреть документальные фильмы?",
    "Какой документальный фильм тебе запомнился?",
    "Ты когда-нибудь пробовал заниматься спортом на свежем воздухе?",
    "Какой твой любимый вид активного отдыха?",
    "Ты знаешь, как организовать поездку?",
    "Как ты планируешь свои путешествия?",
    "Ты любишь читать биографии?",
    "Какой биографией ты был впечатлен?",
    "Ты когда-нибудь видел живое выступление?",
    "Какое было твое самое яркое впечатление от концерта?",
    "Ты любишь участвовать в общественной жизни?",
    "Какое волонтерство тебе близко?",
    "Ты когда-нибудь помогал в благотворительности?",
    "Что ты думаешь о социальных сетях?",
    "Ты считаешь, что они полезны или вредны?",
    "Как ты относишься к обсуждению политики?",
    "Как ты видишь свое место в обществе?",
    "Ты любишь делиться своими мыслями с другими?",
    "Что для тебя значит быть открытым человеком?",
    "Ты веришь в хорошее будущее?",
    "Как ты относишься к экологии?",
    "Что ты делаешь для защиты окружающей среды?",
    "Ты часто посещаешь выставки и музеи?",
    "Какой музей тебе понравился больше всего?",
    "Ты когда-нибудь участвовал в культурных мероприятиях?",
    "Какое мероприятие было самым запоминающимся?",
    "Ты любишь заниматься рукоделием?",
    "Какое занятие тебе больше всего нравится?",
    "Ты предпочитаешь одиночество или общество?",
    "Как ты находишь баланс между работой и отдыхом?",
    "Ты часто путешествуешь по России?",
    "Какой город в России тебе нравится больше всего?",
    "Ты думаешь о своем здоровье?",
    "Что ты делаешь для поддержания здоровья?",
    "Ты знаешь какие-нибудь полезные советы по здоровью?",
    "Ты когда-нибудь пробовал заниматься спортом в команде?",
    "Что ты думаешь о командных видах спорта?",
    "Как ты относишься к физическим нагрузкам?",
    "Ты предпочитаешь активный или пассивный отдых?",
    "Как ты относишься к традициям своей страны?",
    "Что для тебя значит культура?",
    "Ты считаешь, что культура важна для развития общества?",
    "Как ты проводишь свободное время?",
    "Ты часто ходишь на концерты?",
    "Что ты думаешь о современном искусстве?",
    "Какое произведение искусства тебе запомнилось?",
    "Ты любишь обсуждать книги?",
    "Какую книгу ты прочитал недавно?",
    "Ты когда-нибудь принимал участие в курсах по саморазвитию?",
    "Какой курс был для тебя полезным?",
]


russian_b1_possible_answers = [
    "what do you think about your job",
    "how do you spend your vacation",
    "do you prefer resting on the beach or in the mountains",
    "what place in the world do you dream of visiting",
    "have you ever tried doing yoga",
    "what is your favorite childhood memory",
    "what do you think about modern technology",
    "how often do you use the internet",
    "do you like spending time in nature",
    "what does family mean to you",
    "can you make something with your hands",
    "how do you maintain your physical shape",
    "have you ever participated in competitions",
    "what do you think about sports as a lifestyle",
    "have you ever learned to play a musical instrument",
    "what is your favorite style of music",
    "what is more important to you: work or personal life",
    "do you prefer working in a team or alone",
    "how do you feel about criticism",
    "what do you think about self-improvement",
    "how do you set goals for the future",
    "have you ever dreamed of becoming famous",
    "what is the most important lesson you have learned in life",
    "do you believe in friendship between a man and a woman",
    "what do you think about love",
    "how do you feel about long-term relationships",
    "do you like to cook for your friends",
    "what is the most unusual experience in your life",
    "have you ever faced difficulties in life",
    "what do you do to cope with stress",
    "have you ever thought about changing your profession",
    "do you think work is important for happiness",
    "do you often communicate with your parents",
    "how do you spend time with friends",
    "what do you do when you feel sad",
    "how do you cheer yourself up",
    "do you like watching documentaries",
    "which documentary impressed you",
    "have you ever tried outdoor sports",
    "what is your favorite type of active recreation",
    "do you know how to organize a trip",
    "how do you plan your travels",
    "do you like reading biographies",
    "which biography impressed you",
    "have you ever seen a live performance",
    "what was your most vivid impression of a concert",
    "do you like participating in public life",
    "what volunteering appeals to you",
    "have you ever helped with charity work",
    "what do you think about social media",
    "do you think they are useful or harmful",
    "how do you feel about discussing politics",
    "how do you see your place in society",
    "do you like sharing your thoughts with others",
    "what does it mean to be an open person",
    "do you believe in a bright future",
    "how do you feel about ecology",
    "what do you do to protect the environment",
    "do you often visit exhibitions and museums",
    "which museum did you like the most",
    "have you ever participated in cultural events",
    "what event was the most memorable",
    "do you like doing handicrafts",
    "what activity do you enjoy the most",
    "do you prefer solitude or company",
    "how do you find balance between work and rest",
    "do you often travel within russia",
    "which city in russia do you like the most",
    "do you think about your health",
    "what do you do to maintain your health",
    "do you know any useful health tips",
    "have you ever tried team sports",
    "what do you think about team sports",
    "how do you feel about physical activity",
    "do you prefer active or passive recreation",
    "how do you feel about the traditions of your country",
    "what does culture mean to you",
    "do you think culture is important for society's development",
    "how do you spend your free time",
    "do you often go to concerts",
    "what do you think about modern art",
    "which artwork impressed you",
    "do you like discussing books",
    "what book did you read recently",
    "have you ever participated in self-improvement courses",
    "which course was useful for you",
]

french_a1_possible_questions = [
    "Bonjour!",
    "Comment ça va?",
    "Je m'appelle Tim.",
    "Quel âge as-tu?",
    "J'aime les pommes.",
    "Où habites-tu?",
    "C'est mon livre.",
    "As-tu des frères ou sœurs?",
    "Quel est ton plat préféré?",
    "Tu parles anglais?",
    "C'est un beau jour.",
    "J'aime écouter de la musique.",
    "Où est la bibliothèque?",
    "As-tu un animal de compagnie?",
    "Quel est ton film préféré?",
    "Qu'est-ce que tu fais aujourd'hui?",
    "J'aime le chocolat.",
    "C'est ma maison.",
    "Quand est ton anniversaire?",
    "Que veux-tu manger?",
    "Tu aimes le sport?",
    "C'est intéressant.",
    "Quelle est ta couleur préférée?",
    "As-tu un hobby?",
    "C'est ta voiture?",
    "Tu veux aller au cinéma?",
    "Quel temps fait-il?",
    "Où est le restaurant?",
    "C'est mon ami.",
    "Tu as un travail?",
    "Qu'est-ce que tu étudies?",
    "C'est ma famille.",
    "Tu aimes voyager?",
    "Quelle est ta saison préférée?",
    "Tu sais cuisiner?",
    "As-tu des questions?",
    "C'est une bonne idée.",
    "Quelle musique aimes-tu?",
    "C'est une belle ville.",
    "As-tu déjà été en France?",
    "Quelle est ta boisson préférée?",
    "Tu regardes la télé?",
    "Quel est ton livre préféré?",
    "As-tu un animal?",
    "Tu fais du sport?",
    "Comment s'appelle ton ami?",
    "Où sont mes clés?",
    "Tu sais parler français?",
    "C'est un bon moment.",
    "Tu as une sœur?",
    "Quelle est ta matière préférée?",
    "C'est un joli paysage.",
    "As-tu un plan pour ce week-end?",
    "Tu veux un café?",
    "C'est un bon film.",
    "Où est la gare?",
]

french_a1_possible_answers = [
    "hello",
    "how are you",
    "my name is tim",
    "i am 20 years old",
    "i like apples",
    "where do you live",
    "this is my book",
    "do you have brothers or sisters",
    "what is your favorite dish",
    "do you speak english",
    "it's a nice day",
    "i like listening to music",
    "where is the library",
    "do you have a pet",
    "what is your favorite movie",
    "what are you doing today",
    "i like chocolate",
    "this is my house",
    "when is your birthday",
    "what do you want to eat",
    "do you like sports",
    "it's interesting",
    "what is your favorite color",
    "do you have a hobby",
    "is this your car",
    "do you want to go to the cinema",
    "what's the weather like",
    "where is the restaurant",
    "this is my friend",
    "do you have a job",
    "what are you studying",
    "this is my family",
    "do you like to travel",
    "what is your favorite season",
    "can you cook",
    "do you have questions",
    "that's a good idea",
    "what music do you like",
    "it's a beautiful city",
    "have you ever been to france",
    "what is your favorite drink",
    "do you watch tv",
    "what is your favorite book",
    "do you have an animal",
    "do you play sports",
    "what is your friend's name",
    "where are my keys",
    "can you speak french",
    "it's a good time",
    "do you have a sister",
    "what is your favorite subject",
    "it's a beautiful landscape",
    "do you have plans for this weekend",
    "do you want a coffee",
    "it's a good movie",
    "where is the train station",
]

french_a2_possible_questions = [
    "Comment s'est passée ta journée?",
    "Qu'est-ce que tu fais normalement le week-end?",
    "Tu vas souvent au cinéma?",
    "Quel est ton film préféré?",
    "Qu'est-ce que tu vas faire demain?",
    "Tu aimes lire des livres?",
    "Quel est ton livre préféré?",
    "Tu parles d'autres langues?",
    "Où est-ce que tu travailles?",
    "Quelle est ton expérience professionnelle?",
    "Tu aimes cuisiner?",
    "Quel est ton plat préféré?",
    "Tu es déjà allé à l'étranger?",
    "Quelle est la ville la plus intéressante que tu as visitée?",
    "Que penses-tu de la langue française?",
    "Tu écoutes de la musique?",
    "Quelle musique aimes-tu?",
    "Quel est ton passe-temps?",
    "Tu fais du sport?",
    "Quel est ton sport préféré?",
    "Tu aimes voyager?",
    "Où voudrais-tu aller?",
    "Quand est ton anniversaire?",
    "Tu fêtes le Nouvel An?",
    "Qu'est-ce que tu cuisines pour les fêtes?",
    "Tu sais faire du vélo?",
    "Tu préfères la montagne ou la mer?",
    "Quelle est ta boisson préférée?",
    "Tu bois du café ou du thé?",
    "À quelle fréquence manges-tu au restaurant?",
    "Tu as déjà joué à des jeux de société?",
    "Quel est ton jeu de société préféré?",
    "Tu aimes les animaux?",
    "As-tu un animal de compagnie?",
    "Tu as déjà fait du bénévolat?",
    "Quel est ton moment le plus mémorable dans la vie?",
    "Tu préfères les fêtes ou les soirées tranquilles?",
    "Comment passes-tu du temps avec tes amis?",
    "Que fais-tu pendant ton temps libre?",
    "Tu aimes l'automne?",
    "Quelle est ta saison préférée?",
    "Tu as écouté de la musique française?",
    "Quel est ton artiste français préféré?",
    "Tu as regardé des séries françaises?",
    "Quelle est ta série préférée?",
    "Tu préfères la nourriture préparée ou faite maison?",
    "Tu as déjà enseigné quelque chose à quelqu'un?",
    "Quelle est la matière la plus difficile à l'école?",
    "Tu aimes dessiner?",
    "Quel est ton artiste préféré?",
    "Tu as déjà écrit de la poésie?",
    "Qu'est-ce qui t'inspire?",
    "Quelle est ta fête préférée?",
    "Tu aimes les surprises?",
    "Quelle surprise te rappelle un bon souvenir?",
    "Tu sais jouer d'un instrument de musique?",
    "Quel instrument joues-tu?",
    "Tu as déjà participé à une pièce de théâtre?",
    "Que penses-tu du théâtre?",
    "Quelle est ta pièce préférée?",
    "Tu sais danser?",
    "Quel style de danse aimes-tu?",
    "Tu as déjà assisté à des ateliers?",
    "Quel atelier aimerais-tu suivre?",
    "Tu aimes les promenades en plein air?",
    "Où aimes-tu te promener?",
    "Quel est ton parc préféré?",
    "Tu aimes regarder des films en version originale?",
    "Quel film as-tu vu récemment?",
    "Que manges-tu généralement au petit-déjeuner?",
    "Que penses-tu de l'alimentation saine?",
    "Tu as déjà essayé le végétarisme?",
    "Quelle est ta variété de thé préférée?",
    "Tu vas souvent aux expositions?",
    "À quelle exposition es-tu allé récemment?",
    "Tu aimes participer à des concours?",
    "Quel concours t'a le plus intéressé?",
    "Tu as déjà rencontré des célébrités?",
    "Quelle célébrité te plaît?",
    "Tu préfères les films ou les livres?",
    "Quel genre préfères-tu?",
    "Tu es déjà allé à un concert?",
    "Quel concert as-tu le plus aimé?",
    "Tu connais des traditions populaires?",
    "Quelle fête préfères-tu?",
    "Tu connais des proverbes français?",
    "Quelle leçon as-tu tirée de ta vie?",
    "Tu crois au destin?",
    "Que penses-tu des coïncidences?",
    "Tu aimes planifier tes activités?",
    "Comment organises-tu ton temps?",
    "Tu sais gérer un budget?",
    "Comment économises-tu de l'argent?",
    "Tu as déjà rêvé de réaliser un rêve?",
    "Qu'est-ce qui est important pour toi dans la vie?",
    "Tu as déjà réfléchi à ton avenir?",
    "Comment imagines-tu ta vie dans cinq ans?",
    "Tu aimes rêver?",
    "Quel est ton rêve le plus cher?",
]

french_a2_possible_answers = [
    "how was your day",
    "what do you usually do on weekends",
    "do you often go to the movies",
    "what is your favorite movie",
    "what will you do tomorrow",
    "do you like reading books",
    "what is your favorite book",
    "do you speak other languages",
    "where do you work",
    "what is your work experience",
    "do you like cooking",
    "what is your favorite dish",
    "have you ever been abroad",
    "what is the most interesting city you visited",
    "what do you think about the french language",
    "do you listen to music",
    "what music do you like",
    "what is your hobby",
    "do you play sports",
    "what is your favorite sport",
    "do you like to travel",
    "where would you like to go",
    "when is your birthday",
    "do you celebrate new year",
    "what do you usually cook for holidays",
    "can you ride a bike",
    "do you prefer mountains or the sea",
    "what is your favorite drink",
    "do you drink coffee or tea",
    "how often do you eat at restaurants",
    "have you ever played board games",
    "what is your favorite board game",
    "do you like animals",
    "do you have a pet",
    "have you ever participated in volunteering",
    "what is your most memorable moment in life",
    "do you prefer parties or quiet evenings",
    "how do you usually spend time with friends",
    "what do you like to do in your free time",
    "do you like autumn",
    "what is your favorite season",
    "have you listened to french music",
    "who is your favorite french artist",
    "have you watched french series",
    "what is your favorite series",
    "do you prefer ready-made food or home-cooked",
    "have you ever taught someone",
    "what is the hardest subject in school",
    "do you like drawing",
    "who is your favorite artist",
    "have you ever written poetry",
    "what inspires you",
    "what is your favorite holiday",
    "do you like surprises",
    "what surprise do you remember",
    "can you play a musical instrument",
    "which instrument do you play",
    "have you ever participated in theater",
    "what do you think about theater",
    "what is your favorite play",
    "can you dance",
    "what style of dance do you like",
    "have you ever attended workshops",
    "which workshop would you like to attend",
    "do you enjoy walks in fresh air",
    "where do you like to walk",
    "what is your favorite park",
    "do you like to watch movies in original language",
    "what movie did you watch recently",
    "what do you usually eat for breakfast",
    "how do you feel about healthy eating",
    "have you ever tried vegetarianism",
    "what is your favorite type of tea",
    "do you often go to exhibitions",
    "which exhibition did you visit recently",
    "do you like to participate in contests",
    "what contest was the most interesting",
    "have you ever met celebrities",
    "who is your favorite celebrity",
    "do you prefer movies or books",
    "what genre do you like more",
    "have you ever been to a concert",
    "what concert was the most memorable",
    "do you know any folk traditions",
    "which holiday do you love the most",
    "do you know any french proverbs",
    "what lesson have you learned from your life",
    "do you believe in fate",
    "how do you feel about coincidences",
    "do you like to plan your affairs",
    "how do you organize your time",
    "can you manage a budget",
    "how do you save money",
    "have you ever dreamed of your dream",
    "what is important to you in life",
    "have you ever thought about the future",
    "how do you see your life in five years",
    "do you like to dream",
    "what is your most cherished dream",
]

french_b1_possible_questions = [
    "Que penses-tu de ton travail?",
    "Comment passes-tu tes vacances?",
    "Tu préfères te détendre à la plage ou à la montagne?",
    "Quel est l'endroit du monde que tu rêves de visiter?",
    "As-tu déjà essayé de faire du yoga?",
    "Quel est ton meilleur souvenir d'enfance?",
    "Que penses-tu des nouvelles technologies?",
    "À quelle fréquence utilises-tu Internet?",
    "Aimes-tu passer du temps dans la nature?",
    "Que signifie pour toi la famille?",
    "Sais-tu faire quelque chose de tes propres mains?",
    "Comment maintiens-tu ta forme physique?",
    "As-tu déjà participé à des compétitions?",
    "Que penses-tu du sport comme mode de vie?",
    "As-tu déjà appris à jouer d'un instrument de musique?",
    "Quel est ton style de musique préféré?",
    "Qu'est-ce qui est plus important pour toi: le travail ou la vie personnelle?",
    "Préfères-tu travailler en équipe ou seul?",
    "Que penses-tu de la critique?",
    "Que penses-tu du développement personnel?",
    "Comment fixeras-tu tes objectifs pour l'avenir?",
    "As-tu déjà rêvé de devenir célèbre?",
    "Quelle est la leçon la plus importante que tu aies apprise dans ta vie?",
    "Crois-tu en l'amitié entre un homme et une femme?",
    "Que penses-tu de l'amour?",
    "Comment vois-tu les relations à long terme?",
    "Aimes-tu cuisiner pour tes amis?",
    "Quelle est la plus étrange expérience de ta vie?",
    "As-tu déjà rencontré des difficultés dans la vie?",
    "Que fais-tu pour gérer le stress?",
    "As-tu déjà pensé à changer de profession?",
    "Penses-tu que le travail est important pour le bonheur?",
    "Communiques-tu souvent avec tes parents?",
    "Comment passes-tu du temps avec tes amis?",
    "Que fais-tu quand tu es triste?",
    "Comment te remontes-tu le moral?",
    "Aimes-tu regarder des documentaires?",
    "Quel documentaire t'a le plus marqué?",
    "As-tu déjà essayé de faire du sport en plein air?",
    "Quel est ton type de loisirs actif préféré?",
    "Sais-tu organiser un voyage?",
    "Comment prépares-tu tes voyages?",
    "Aimes-tu lire des biographies?",
    "Quelle biographie t'a impressionné?",
    "As-tu déjà assisté à un spectacle en direct?",
    "Quelle a été ta plus vive impression d'un concert?",
    "Aimes-tu participer à la vie publique?",
    "Quel type de bénévolat t'attire?",
    "As-tu déjà aidé dans des œuvres de charité?",
    "Que penses-tu des réseaux sociaux?",
    "Les trouves-tu utiles ou nuisibles?",
    "Comment vois-tu la discussion politique?",
    "Comment vois-tu ta place dans la société?",
    "Aimes-tu partager tes pensées avec les autres?",
    "Que signifie pour toi être une personne ouverte?",
    "Crois-tu en un avenir meilleur?",
    "Comment penses-tu à l'écologie?",
    "Que fais-tu pour protéger l'environnement?",
    "Visites-tu souvent des expositions et des musées?",
    "Quel musée t'a le plus plu?",
    "As-tu déjà participé à des événements culturels?",
    "Quel événement était le plus mémorable?",
    "Aimes-tu faire des travaux manuels?",
    "Quelle activité aimes-tu le plus?",
    "Préfères-tu la solitude ou la compagnie?",
    "Comment trouves-tu l'équilibre entre le travail et le repos?",
    "Voyages-tu souvent à l'intérieur de la France?",
    "Quelle ville en France préfères-tu?",
    "Penses-tu à ta santé?",
    "Que fais-tu pour maintenir ta santé?",
    "Connais-tu des conseils utiles sur la santé?",
    "As-tu déjà essayé le sport en équipe?",
    "Que penses-tu des sports d'équipe?",
    "Comment vois-tu l'activité physique?",
    "Préfères-tu les loisirs actifs ou passifs?",
    "Que penses-tu des traditions de ton pays?",
    "Que signifie pour toi la culture?",
    "Penses-tu que la culture est importante pour le développement de la société?",
    "Comment passes-tu ton temps libre?",
    "Vas-tu souvent à des concerts?",
    "Que penses-tu de l'art moderne?",
    "Quelle œuvre d'art t'a marqué?",
    "Aimes-tu discuter des livres?",
    "Quel livre as-tu lu récemment?",
    "As-tu déjà participé à des cours de développement personnel?",
    "Quel cours t'a été utile?",
]

french_b1_possible_answers = [
    "what do you think about your job",
    "how do you spend your vacation",
    "do you prefer relaxing on the beach or in the mountains",
    "what place in the world do you dream of visiting",
    "have you ever tried doing yoga",
    "what is your best childhood memory",
    "what do you think about modern technology",
    "how often do you use the internet",
    "do you like spending time in nature",
    "what does family mean to you",
    "can you make something with your hands",
    "how do you maintain your physical shape",
    "have you ever participated in competitions",
    "what do you think about sports as a lifestyle",
    "have you ever learned to play a musical instrument",
    "what is your favorite style of music",
    "what is more important to you: work or personal life",
    "do you prefer working in a team or alone",
    "how do you feel about criticism",
    "what do you think about self-improvement",
    "how do you set goals for the future",
    "have you ever dreamed of becoming famous",
    "what is the most important lesson you have learned in life",
    "do you believe in friendship between a man and a woman",
    "what do you think about love",
    "how do you feel about long-term relationships",
    "do you like to cook for your friends",
    "what is the most unusual experience in your life",
    "have you ever faced difficulties in life",
    "what do you do to cope with stress",
    "have you ever thought about changing your profession",
    "do you think work is important for happiness",
    "do you often communicate with your parents",
    "how do you spend time with friends",
    "what do you do when you feel sad",
    "how do you cheer yourself up",
    "do you like watching documentaries",
    "which documentary impressed you",
    "have you ever tried outdoor sports",
    "what is your favorite type of active recreation",
    "do you know how to organize a trip",
    "how do you plan your travels",
    "do you like reading biographies",
    "which biography impressed you",
    "have you ever seen a live performance",
    "what was your most vivid impression of a concert",
    "do you like participating in public life",
    "what volunteering appeals to you",
    "have you ever helped with charity work",
    "what do you think about social media",
    "do you think they are useful or harmful",
    "how do you feel about discussing politics",
    "how do you see your place in society",
    "do you like sharing your thoughts with others",
    "what does it mean to be an open person",
    "do you believe in a bright future",
    "how do you feel about ecology",
    "what do you do to protect the environment",
    "do you often visit exhibitions and museums",
    "which museum did you like the most",
    "have you ever participated in cultural events",
    "what event was the most memorable",
    "do you like doing handicrafts",
    "what activity do you enjoy the most",
    "do you prefer solitude or company",
    "how do you find balance between work and rest",
    "do you often travel within France",
    "which city in France do you like the most",
    "do you think about your health",
    "what do you do to maintain your health",
    "do you know any useful health tips",
    "have you ever tried team sports",
    "what do you think about team sports",
    "how do you feel about physical activity",
    "do you prefer active or passive recreation",
    "how do you feel about the traditions of your country",
    "what does culture mean to you",
    "do you think culture is important for society's development",
    "how do you spend your free time",
    "do you often go to concerts",
    "what do you think about modern art",
    "which artwork impressed you",
    "do you like discussing books",
    "what book did you read recently",
    "have you ever participated in self-improvement courses",
    "which course was useful for you",
]

spanish_a1_possible_questions = [
    "¡Hola!",
    "¿Cómo estás?",
    "Soy Tim.",
    "¿Cómo te llamas?",
    "Tengo 20 años.",
    "¿Dónde vives?",
    "Me gusta la pizza.",
    "¿Hablas inglés?",
    "¿Qué es esto?",
    "¿Cuál es tu color favorito?",
    "¿Tienes hermanos?",
    "¿Cuál es tu animal favorito?",
    "¿Te gusta el deporte?",
    "¿Qué te gusta hacer en tu tiempo libre?",
    "¿Cuál es tu comida favorita?",
    "¿Te gusta el helado?",
    "¿Cuál es tu estación favorita?",
    "¿Te gusta viajar?",
    "¿Dónde quieres ir de vacaciones?",
    "¿Tienes una mascota?",
    "¿Te gusta la música?",
    "¿Cuál es tu banda favorita?",
    "¿Qué hora es?",
    "¿Cuántos años tienes?",
    "¿Dónde estudias?",
    "¿Cuál es tu materia favorita?",
    "¿Te gusta bailar?",
    "¿Qué deporte practicas?",
    "¿Tienes amigos en la escuela?",
    "¿Cuál es tu película favorita?",
    "¿Te gusta leer?",
    "¿Qué libro te gusta?",
    "¿Tienes teléfono móvil?",
    "¿Cuál es tu número de teléfono?",
    "¿Te gusta salir con amigos?",
    "¿Cuál es tu lugar favorito en la ciudad?",
    "¿Te gusta cocinar?",
    "¿Cuál es tu receta favorita?",
    "¿Qué haces los fines de semana?",
    "¿Te gusta la playa?",
    "¿Cuándo es tu cumpleaños?",
    "¿Cuál es tu fruta favorita?",
    "¿Te gusta el chocolate?",
    "¿Qué tipo de películas prefieres?",
    "¿Tienes un coche?",
    "¿Qué haces para relajarte?",
    "¿Te gusta el arte?",
    "¿Cuál es tu artista favorito?",
    "¿Tienes una computadora?",
    "¿Qué juegos te gustan?",
    "¿Te gusta el invierno?",
    "¿Cuál es tu deporte favorito?",
    "¿Qué música escuchas?",
    "¿Te gusta hacer ejercicio?",
    "¿Cuál es tu programa de televisión favorito?",
    "¿Qué tipo de comida prefieres?",
    "¿Te gusta hacer nuevas amistades?",
    "¿Tienes un amigo especial?",
    "¿Cuál es tu día favorito de la semana?",
    "¿Te gusta la comida rápida?",
    "¿Cuál es tu bebida favorita?",
    "¿Qué tipo de clima prefieres?",
    "¿Tienes una actividad favorita?",
    "¿Te gusta el café?",
    "¿Qué haces por la mañana?",
    "¿Tienes un pasatiempo?",
    "¿Qué haces en tu tiempo libre?",
    "¿Tienes un sueño?",
    "¿Te gusta visitar museos?",
    "¿Cuál es tu museo favorito?",
    "¿Qué tipo de vacaciones prefieres?",
    "¿Te gusta ir de compras?",
    "¿Cuál es tu marca favorita?",
    "¿Qué te gusta hacer los domingos?",
    "¿Cuál es tu fruta favorita?",
    "¿Te gusta la naturaleza?",
    "¿Cuál es tu lugar favorito para relajarte?",
    "¿Qué te gustaría aprender?",
    "¿Tienes algún talento especial?",
    "¿Te gusta la historia?",
    "¿Cuál es tu momento favorito del día?",
    "¿Te gusta el sushi?",
    "¿Cómo celebras tu cumpleaños?",
    "¿Te gusta la poesía?",
    "¿Cuál es tu estación del año favorita?",
    "¿Te gusta ayudar a los demás?",
    "¿Tienes algún sueño por cumplir?",
    "¿Cuál es tu ciudad favorita?",
    "¿Te gusta hacer manualidades?",
    "¿Tienes una rutina diaria?",
    "¿Qué tipo de serie prefieres?",
    "¿Te gustaría conocer a alguien famoso?",
    "¿Qué es lo que más valoras en una amistad?",
]

spanish_a1_possible_answers = [
    "hello",
    "how are you",
    "i am tim",
    "what is your name",
    "i am 20 years old",
    "where do you live",
    "i like pizza",
    "do you speak english",
    "what is this",
    "what is your favorite color",
    "do you have siblings",
    "what is your favorite animal",
    "do you like sports",
    "what do you like to do in your free time",
    "what is your favorite food",
    "do you like ice cream",
    "what is your favorite season",
    "do you like to travel",
    "where do you want to go on vacation",
    "do you have a pet",
    "do you like music",
    "who is your favorite band",
    "what time is it",
    "how old are you",
    "where do you study",
    "what is your favorite subject",
    "do you like to dance",
    "what sport do you practice",
    "do you have friends at school",
    "what is your favorite movie",
    "do you like to read",
    "what book do you like",
    "do you have a mobile phone",
    "what is your phone number",
    "do you like to go out with friends",
    "what is your favorite place in the city",
    "do you like to cook",
    "what is your favorite recipe",
    "what do you do on weekends",
    "do you like the beach",
    "when is your birthday",
    "what is your favorite fruit",
    "do you like chocolate",
    "what type of movies do you prefer",
    "do you have a car",
    "what do you do to relax",
    "do you like art",
    "who is your favorite artist",
    "do you have a computer",
    "what games do you like",
    "do you like winter",
    "what is your favorite sport",
    "what music do you listen to",
    "do you like to exercise",
    "what is your favorite TV show",
    "what type of food do you prefer",
    "do you like to make new friends",
    "do you have a special friend",
    "what is your favorite day of the week",
    "do you like fast food",
    "what is your favorite drink",
    "what type of weather do you prefer",
    "do you have a favorite activity",
    "do you like coffee",
    "what do you do in the morning",
    "do you have a hobby",
    "what do you do in your free time",
    "do you have a dream",
    "do you like to visit museums",
    "what is your favorite museum",
    "what type of vacation do you prefer",
    "do you like shopping",
    "what is your favorite brand",
    "what do you like to do on Sundays",
    "what is your favorite fruit",
    "do you like nature",
    "what is your favorite place to relax",
    "what would you like to learn",
    "do you have a special talent",
    "do you like history",
    "what is your favorite time of day",
    "do you like sushi",
    "how do you celebrate your birthday",
    "do you like poetry",
    "what is your favorite season of the year",
    "do you like to help others",
    "do you have a dream to fulfill",
    "what is your favorite city",
    "do you like to do crafts",
    "do you have a daily routine",
    "what type of series do you prefer",
    "would you like to meet someone famous",
    "what do you value most in a friendship",
]


spanish_a2_possible_questions = [
    "¿Cómo fue tu día?",
    "¿Qué sueles hacer los fines de semana?",
    "¿Vas al cine a menudo?",
    "¿Cuál es tu película favorita?",
    "¿Qué vas a hacer mañana?",
    "¿Te gusta leer libros?",
    "¿Cuál es tu libro favorito?",
    "¿Hablas otros idiomas?",
    "¿Dónde trabajas?",
    "¿Cuál es tu experiencia laboral?",
    "¿Te gusta cocinar?",
    "¿Cuál es tu plato favorito?",
    "¿Has viajado al extranjero?",
    "¿Cuál es la ciudad más interesante que has visitado?",
    "¿Qué piensas del idioma español?",
    "¿Escuchas música?",
    "¿Qué música te gusta?",
    "¿Cuál es tu pasatiempo?",
    "¿Practicas deportes?",
    "¿Cuál es tu deporte favorito?",
    "¿Te gusta viajar?",
    "¿A dónde te gustaría ir?",
    "¿Cuándo es tu cumpleaños?",
    "¿Celebras el Año Nuevo?",
    "¿Qué cocinas para las fiestas?",
    "¿Sabes andar en bicicleta?",
    "¿Prefieres la montaña o la playa?",
    "¿Cuál es tu bebida favorita?",
    "¿Bebes café o té?",
    "¿Con qué frecuencia comes en restaurantes?",
    "¿Has jugado a juegos de mesa?",
    "¿Cuál es tu juego de mesa favorito?",
    "¿Te gustan los animales?",
    "¿Tienes una mascota?",
    "¿Has hecho trabajo voluntario?",
    "¿Cuál es tu recuerdo más memorable?",
    "¿Prefieres fiestas o noches tranquilas?",
    "¿Cómo pasas tiempo con tus amigos?",
    "¿Qué haces en tu tiempo libre?",
    "¿Te gusta el otoño?",
    "¿Cuál es tu estación favorita?",
    "¿Has escuchado música en español?",
    "¿Quién es tu artista español favorito?",
    "¿Has visto series españolas?",
    "¿Cuál es tu serie favorita?",
    "¿Prefieres comida hecha o comida rápida?",
    "¿Alguna vez has enseñado algo a alguien?",
    "¿Cuál es la materia más difícil en la escuela?",
    "¿Te gusta dibujar?",
    "¿Quién es tu artista favorito?",
    "¿Has escrito poesía?",
    "¿Qué te inspira?",
    "¿Cuál es tu fiesta favorita?",
    "¿Te gustan las sorpresas?",
    "¿Qué sorpresa te trae un buen recuerdo?",
    "¿Sabes tocar un instrumento musical?",
    "¿Qué instrumento tocas?",
    "¿Has participado en una obra de teatro?",
    "¿Qué piensas del teatro?",
    "¿Cuál es tu obra favorita?",
    "¿Sabes bailar?",
    "¿Qué estilo de baile te gusta?",
    "¿Has asistido a talleres?",
    "¿Qué taller te gustaría hacer?",
    "¿Te gustan las caminatas al aire libre?",
    "¿Dónde te gusta caminar?",
    "¿Cuál es tu parque favorito?",
    "¿Te gusta ver películas en versión original?",
    "¿Qué película has visto recientemente?",
    "¿Qué sueles comer para el desayuno?",
    "¿Qué piensas de la alimentación saludable?",
    "¿Alguna vez has probado ser vegetariano?",
    "¿Cuál es tu tipo de té favorito?",
    "¿Vas a menudo a exposiciones?",
    "¿A qué exposición fuiste recientemente?",
    "¿Te gusta participar en concursos?",
    "¿Qué concurso te ha interesado más?",
    "¿Alguna vez has conocido a celebridades?",
    "¿Qué celebridad te gusta?",
    "¿Prefieres películas o libros?",
    "¿Qué género prefieres?",
    "¿Has ido a un concierto?",
    "¿Cuál concierto te gustó más?",
    "¿Conoces tradiciones populares?",
    "¿Cuál es tu fiesta preferida?",
    "¿Conoces refranes españoles?",
    "¿Qué lección has aprendido de tu vida?",
    "¿Crees en el destino?",
    "¿Qué piensas de las coincidencias?",
    "¿Te gusta planificar tus actividades?",
    "¿Cómo organizas tu tiempo?",
    "¿Sabes manejar un presupuesto?",
    "¿Cómo ahorras dinero?",
    "¿Alguna vez has soñado con realizar un sueño?",
    "¿Qué es importante para ti en la vida?",
    "¿Alguna vez has reflexionado sobre tu futuro?",
    "¿Cómo imaginas tu vida en cinco años?",
    "¿Te gusta soñar?",
    "¿Cuál es tu sueño más querido?",
]

spanish_a2_possible_answers = [
    "how was your day",
    "what do you usually do on weekends",
    "do you often go to the movies",
    "what is your favorite movie",
    "what will you do tomorrow",
    "do you like reading books",
    "what is your favorite book",
    "do you speak other languages",
    "where do you work",
    "what is your work experience",
    "do you like cooking",
    "what is your favorite dish",
    "have you ever been abroad",
    "what is the most interesting city you visited",
    "what do you think about the spanish language",
    "do you listen to music",
    "what music do you like",
    "what is your hobby",
    "do you play sports",
    "what is your favorite sport",
    "do you like to travel",
    "where would you like to go",
    "when is your birthday",
    "do you celebrate new year",
    "what do you usually cook for holidays",
    "can you ride a bike",
    "do you prefer mountains or the sea",
    "what is your favorite drink",
    "do you drink coffee or tea",
    "how often do you eat at restaurants",
    "have you ever played board games",
    "what is your favorite board game",
    "do you like animals",
    "do you have a pet",
    "have you ever done volunteer work",
    "what is your most memorable memory",
    "do you prefer parties or quiet nights",
    "how do you spend time with your friends",
    "what do you do in your free time",
    "do you like autumn",
    "what is your favorite season",
    "have you listened to spanish music",
    "who is your favorite spanish artist",
    "have you watched spanish series",
    "what is your favorite series",
    "do you prefer homemade food or fast food",
    "have you ever taught someone something",
    "what is the hardest subject in school",
    "do you like drawing",
    "who is your favorite artist",
    "have you written poetry",
    "what inspires you",
    "what is your favorite holiday",
    "do you like surprises",
    "what surprise brings you a good memory",
    "can you play a musical instrument",
    "which instrument do you play",
    "have you participated in a play",
    "what do you think about theater",
    "what is your favorite play",
    "can you dance",
    "what style of dance do you like",
    "have you attended workshops",
    "which workshop would you like to do",
    "do you like walks in the fresh air",
    "where do you like to walk",
    "what is your favorite park",
    "do you like to watch movies in original language",
    "what movie did you watch recently",
    "what do you usually eat for breakfast",
    "how do you feel about healthy eating",
    "have you ever tried being vegetarian",
    "what is your favorite type of tea",
    "do you often go to exhibitions",
    "which exhibition did you visit recently",
    "do you like to participate in contests",
    "what contest has interested you the most",
    "have you ever met celebrities",
    "who is your favorite celebrity",
    "do you prefer movies or books",
    "what genre do you prefer",
    "have you been to a concert",
    "which concert did you like the most",
    "do you know any popular traditions",
    "what is your favorite holiday",
    "do you know any spanish proverbs",
    "what lesson have you learned from your life",
    "do you believe in destiny",
    "what do you think about coincidences",
    "do you like to plan your activities",
    "how do you organize your time",
    "can you manage a budget",
    "how do you save money",
    "have you ever dreamed of realizing a dream",
    "what is important to you in life",
    "have you ever thought about your future",
    "how do you imagine your life in five years",
    "do you like to dream",
    "what is your most cherished dream",
]

spanish_b1_possible_questions = [
    "¿Qué piensas de tu trabajo?",
    "¿Cómo pasas tus vacaciones?",
    "¿Prefieres descansar en la playa o en las montañas?",
    "¿Cuál es el lugar del mundo que sueñas con visitar?",
    "¿Alguna vez has probado hacer yoga?",
    "¿Cuál es tu recuerdo favorito de la infancia?",
    "¿Qué piensas de las tecnologías modernas?",
    "¿Con qué frecuencia usas Internet?",
    "¿Te gusta pasar tiempo en la naturaleza?",
    "¿Qué significa para ti la familia?",
    "¿Sabes hacer algo con tus manos?",
    "¿Cómo mantienes tu forma física?",
    "¿Has participado alguna vez en competiciones?",
    "¿Qué piensas del deporte como estilo de vida?",
    "¿Has aprendido a tocar un instrumento musical?",
    "¿Cuál es tu estilo de música favorito?",
    "¿Qué es más importante para ti: el trabajo o la vida personal?",
    "¿Prefieres trabajar en equipo o solo?",
    "¿Qué piensas de la crítica?",
    "¿Qué piensas del desarrollo personal?",
    "¿Cómo establecerás tus objetivos para el futuro?",
    "¿Alguna vez has soñado con ser famoso?",
    "¿Cuál es la lección más importante que has aprendido en tu vida?",
    "¿Crees en la amistad entre un hombre y una mujer?",
    "¿Qué piensas del amor?",
    "¿Cómo ves las relaciones a largo plazo?",
    "¿Te gusta cocinar para tus amigos?",
    "¿Cuál ha sido la experiencia más extraña de tu vida?",
    "¿Alguna vez has enfrentado dificultades en la vida?",
    "¿Qué haces para manejar el estrés?",
    "¿Alguna vez has pensado en cambiar de profesión?",
    "¿Crees que el trabajo es importante para la felicidad?",
    "¿Te comunicas a menudo con tus padres?",
    "¿Cómo pasas tiempo con tus amigos?",
    "¿Qué haces cuando te sientes triste?",
    "¿Cómo te animas?",
    "¿Te gusta ver documentales?",
    "¿Qué documental te ha impresionado más?",
    "¿Alguna vez has probado hacer deporte al aire libre?",
    "¿Cuál es tu tipo de ocio activo favorito?",
    "¿Sabes organizar un viaje?",
    "¿Cómo preparas tus viajes?",
    "¿Te gusta leer biografías?",
    "¿Qué biografía te ha impresionado?",
    "¿Alguna vez has asistido a un espectáculo en vivo?",
    "¿Cuál ha sido tu impresión más viva de un concierto?",
    "¿Te gusta participar en la vida pública?",
    "¿Qué tipo de voluntariado te atrae?",
    "¿Alguna vez has ayudado en obras de caridad?",
    "¿Qué piensas de las redes sociales?",
    "¿Las consideras útiles o perjudiciales?",
    "¿Cómo ves la discusión política?",
    "¿Cómo ves tu lugar en la sociedad?",
    "¿Te gusta compartir tus pensamientos con los demás?",
    "¿Qué significa para ti ser una persona abierta?",
    "¿Crees en un futuro mejor?",
    "¿Cómo piensas sobre la ecología?",
    "¿Qué haces para proteger el medio ambiente?",
    "¿Visitas a menudo exposiciones y museos?",
    "¿Qué museo te ha gustado más?",
    "¿Alguna vez has participado en eventos culturales?",
    "¿Cuál evento fue el más memorable?",
    "¿Te gusta hacer manualidades?",
    "¿Qué actividad disfrutas más?",
    "¿Prefieres la soledad o la compañía?",
    "¿Cómo encuentras el equilibrio entre el trabajo y el descanso?",
    "¿Viajas a menudo por España?",
    "¿Qué ciudad de España prefieres?",
    "¿Piensas en tu salud?",
    "¿Qué haces para mantenerte sano?",
    "¿Conoces algún consejo útil sobre salud?",
    "¿Alguna vez has probado deportes en equipo?",
    "¿Qué piensas de los deportes en equipo?",
    "¿Cómo ves la actividad física?",
    "¿Prefieres ocio activo o pasivo?",
    "¿Qué piensas de las tradiciones de tu país?",
    "¿Qué significa para ti la cultura?",
    "¿Crees que la cultura es importante para el desarrollo de la sociedad?",
    "¿Cómo pasas tu tiempo libre?",
    "¿Vas a menudo a conciertos?",
    "¿Qué piensas del arte moderno?",
    "¿Qué obra de arte te ha impresionado?",
    "¿Te gusta discutir sobre libros?",
    "¿Qué libro has leído recientemente?",
    "¿Alguna vez has participado en cursos de desarrollo personal?",
    "¿Qué curso te ha sido útil?",
]

spanish_b1_possible_answers = [
    "what do you think about your job",
    "how do you spend your vacation",
    "do you prefer relaxing on the beach or in the mountains",
    "what place in the world do you dream of visiting",
    "have you ever tried doing yoga",
    "what is your best childhood memory",
    "what do you think about modern technology",
    "how often do you use the internet",
    "do you like spending time in nature",
    "what does family mean to you",
    "can you make something with your hands",
    "how do you maintain your physical shape",
    "have you ever participated in competitions",
    "what do you think about sports as a lifestyle",
    "have you ever learned to play a musical instrument",
    "what is your favorite style of music",
    "what is more important to you: work or personal life",
    "do you prefer working in a team or alone",
    "how do you feel about criticism",
    "what do you think about self-improvement",
    "how do you set goals for the future",
    "have you ever dreamed of becoming famous",
    "what is the most important lesson you have learned in life",
    "do you believe in friendship between a man and a woman",
    "what do you think about love",
    "how do you feel about long-term relationships",
    "do you like to cook for your friends",
    "what is the most unusual experience in your life",
    "have you ever faced difficulties in life",
    "what do you do to cope with stress",
    "have you ever thought about changing your profession",
    "do you think work is important for happiness",
    "do you often communicate with your parents",
    "how do you spend time with friends",
    "what do you do when you feel sad",
    "how do you cheer yourself up",
    "do you like watching documentaries",
    "which documentary impressed you",
    "have you ever tried outdoor sports",
    "what is your favorite type of active recreation",
    "do you know how to organize a trip",
    "how do you plan your travels",
    "do you like reading biographies",
    "which biography impressed you",
    "have you ever seen a live performance",
    "what was your most vivid impression of a concert",
    "do you like participating in public life",
    "what volunteering appeals to you",
    "have you ever helped with charity work",
    "what do you think about social media",
    "do you think they are useful or harmful",
    "how do you feel about discussing politics",
    "how do you see your place in society",
    "do you like sharing your thoughts with others",
    "what does it mean to be an open person",
    "do you believe in a bright future",
    "how do you feel about ecology",
    "what do you do to protect the environment",
    "do you often visit exhibitions and museums",
    "which museum did you like the most",
    "have you ever participated in cultural events",
    "what event was the most memorable",
    "do you like doing handicrafts",
    "what activity do you enjoy the most",
    "do you prefer solitude or company",
    "how do you find balance between work and rest",
    "do you often travel within Spain",
    "which city in Spain do you like the most",
    "do you think about your health",
    "what do you do to maintain your health",
    "do you know any useful health tips",
    "have you ever tried team sports",
    "what do you think about team sports",
    "how do you feel about physical activity",
    "do you prefer active or passive recreation",
    "how do you feel about the traditions of your country",
    "what does culture mean to you",
    "do you think culture is important for society's development",
    "how do you spend your free time",
    "do you often go to concerts",
    "what do you think about modern art",
    "which artwork impressed you",
    "do you like discussing books",
    "what book did you read recently",
    "have you ever participated in self-improvement courses",
    "which course was useful for you",
]

chinese_a1_possible_questions = [
    "你好！",
    "你好吗？",
    "我叫Tim。",
    "你叫什么名字？",
    "我20岁。",
    "你住在哪里？",
    "我喜欢披萨。",
    "你会说英语吗？",
    "这是什么？",
    "你最喜欢的颜色是什么？",
    "你有兄弟姐妹吗？",
    "你最喜欢的动物是什么？",
    "你喜欢运动吗？",
    "你喜欢做什么？",
    "你最喜欢的食物是什么？",
    "你喜欢冰淇淋吗？",
    "你最喜欢的季节是什么？",
    "你喜欢旅行吗？",
    "你想去哪儿度假？",
    "你有宠物吗？",
    "你喜欢音乐吗？",
    "你最喜欢的乐队是谁？",
    "现在几点了？",
    "你几岁？",
    "你在哪里学习？",
    "你最喜欢的科目是什么？",
    "你喜欢跳舞吗？",
    "你在做什么运动？",
    "你在学校有朋友吗？",
    "你最喜欢的电影是什么？",
    "你喜欢阅读吗？",
    "你最喜欢的书是什么？",
    "你有手机吗？",
    "你的电话号码是多少？",
    "你喜欢和朋友出去吗？",
    "你最喜欢的城市在哪里？",
    "你喜欢做饭吗？",
    "你最喜欢的菜谱是什么？",
    "你周末做什么？",
    "你喜欢海滩吗？",
    "你的生日是什么时候？",
    "你最喜欢的水果是什么？",
    "你喜欢巧克力吗？",
    "你喜欢什么类型的电影？",
    "你有车吗？",
    "你做什么来放松？",
    "你喜欢艺术吗？",
    "你最喜欢的艺术家是谁？",
    "你有电脑吗？",
    "你喜欢什么游戏？",
    "你喜欢冬天吗？",
    "你最喜欢的运动是什么？",
    "你听什么音乐？",
    "你喜欢锻炼吗？",
    "你最喜欢的电视节目是什么？",
    "你喜欢什么类型的食物？",
    "你喜欢交新朋友吗？",
    "你有特别的朋友吗？",
    "你最喜欢的一天是什么？",
    "你喜欢快餐吗？",
    "你最喜欢的饮料是什么？",
    "你喜欢什么样的天气？",
    "你有喜欢的活动吗？",
    "你喜欢咖啡吗？",
    "你早上做什么？",
    "你有爱好吗？",
    "你在空闲时间做什么？",
    "你有梦想吗？",
    "你喜欢参观博物馆吗？",
    "你最喜欢的博物馆是什么？",
    "你喜欢什么类型的假期？",
    "你喜欢购物吗？",
    "你最喜欢的品牌是什么？",
    "你周日做什么？",
    "你最喜欢的水果是什么？",
    "你喜欢大自然吗？",
    "你最喜欢的放松地点在哪里？",
    "你想学什么？",
    "你有特别的才能吗？",
    "你喜欢历史吗？",
    "你最喜欢的时间是什么？",
    "你喜欢寿司吗？",
    "你是怎么庆祝生日的？",
    "你喜欢诗歌吗？",
    "你最喜欢的季节是什么？",
    "你喜欢帮助别人吗？",
    "你有想实现的梦想吗？",
    "你最喜欢的城市是哪座？",
    "你喜欢手工艺吗？",
    "你有日常计划吗？",
    "你喜欢什么类型的剧集？",
    "你想认识名人吗？",
    "你最看重友谊中的什么？",
]

chinese_a1_possible_answers = [
    "hello",
    "how are you",
    "i am tim",
    "what is your name",
    "i am 20 years old",
    "where do you live",
    "i like pizza",
    "do you speak english",
    "what is this",
    "what is your favorite color",
    "do you have siblings",
    "what is your favorite animal",
    "do you like sports",
    "what do you like to do",
    "what is your favorite food",
    "do you like ice cream",
    "what is your favorite season",
    "do you like to travel",
    "where do you want to go on vacation",
    "do you have a pet",
    "do you like music",
    "who is your favorite band",
    "what time is it",
    "how old are you",
    "where do you study",
    "what is your favorite subject",
    "do you like to dance",
    "what sport do you practice",
    "do you have friends at school",
    "what is your favorite movie",
    "do you like to read",
    "what book do you like",
    "do you have a mobile phone",
    "what is your phone number",
    "do you like to go out with friends",
    "what is your favorite place in the city",
    "do you like to cook",
    "what is your favorite recipe",
    "what do you do on weekends",
    "do you like the beach",
    "when is your birthday",
    "what is your favorite fruit",
    "do you like chocolate",
    "what type of movies do you prefer",
    "do you have a car",
    "what do you do to relax",
    "do you like art",
    "who is your favorite artist",
    "do you have a computer",
    "what games do you like",
    "do you like winter",
    "what is your favorite sport",
    "what music do you listen to",
    "do you like to exercise",
    "what is your favorite TV show",
    "what type of food do you prefer",
    "do you like to make new friends",
    "do you have a special friend",
    "what is your favorite day of the week",
    "do you like fast food",
    "what is your favorite drink",
    "what type of weather do you prefer",
    "do you have a favorite activity",
    "do you like coffee",
    "what do you do in the morning",
    "do you have a hobby",
    "what do you do in your free time",
    "do you have a dream",
    "do you like to visit museums",
    "what is your favorite museum",
    "what type of vacation do you prefer",
    "do you like shopping",
    "what is your favorite brand",
    "what do you like to do on Sundays",
    "what is your favorite fruit",
    "do you like nature",
    "what is your favorite place to relax",
    "what would you like to learn",
    "do you have a special talent",
    "do you like history",
    "what is your favorite time of day",
    "do you like sushi",
    "how do you celebrate your birthday",
    "do you like poetry",
    "what is your favorite season of the year",
    "do you like to help others",
    "do you have a dream to fulfill",
    "what is your favorite city",
    "do you like to do crafts",
    "do you have a daily routine",
    "what type of series do you prefer",
    "would you like to meet someone famous",
    "what do you value most in a friendship",
]

chinese_a2_possible_questions = [
    "你今天过得怎么样？",
    "你周末通常做什么？",
    "你常常去电影院吗？",
    "你最喜欢的电影是什么？",
    "你明天有什么计划？",
    "你喜欢阅读吗？",
    "你最喜欢的书是什么？",
    "你会说哪些语言？",
    "你在哪里工作？",
    "你有工作经验吗？",
    "你喜欢做饭吗？",
    "你最喜欢的食物是什么？",
    "你曾经去过国外吗？",
    "你去过的最有趣的城市是哪里？",
    "你对中文有什么看法？",
    "你听音乐吗？",
    "你喜欢什么类型的音乐？",
    "你的爱好是什么？",
    "你做什么运动？",
    "你最喜欢的运动是什么？",
    "你喜欢旅行吗？",
    "你想去哪儿旅行？",
    "你生日是什么时候？",
    "你庆祝新年吗？",
    "你过生日时会吃什么？",
    "你会骑自行车吗？",
    "你喜欢山还是海？",
    "你最喜欢的饮料是什么？",
    "你喝咖啡还是茶？",
    "你多久去一次餐厅？",
    "你玩过棋类游戏吗？",
    "你最喜欢的棋类游戏是什么？",
    "你有宠物吗？",
    "你的宠物叫什么名字？",
    "你喜欢参加派对吗？",
    "你常常和朋友一起玩吗？",
    "你会跳舞吗？",
    "你有参加过什么比赛吗？",
    "你觉得锻炼重要吗？",
    "你喜欢参加什么类型的活动？",
    "你对未来有什么计划？",
    "你想学习什么新技能？",
    "你觉得哪种运动最有趣？",
    "你喜欢上网吗？",
    "你经常上社交媒体吗？",
    "你有没有看过电视剧？",
    "你喜欢哪个电视剧？",
    "你会演奏乐器吗？",
    "你想学哪个乐器？",
    "你喜欢看直播吗？",
    "你认为什么是健康的饮食？",
    "你觉得休息重要吗？",
    "你周末喜欢做什么？",
    "你对环保有兴趣吗？",
    "你喜欢园艺吗？",
    "你常常去购物吗？",
    "你喜欢买什么东西？",
    "你最喜欢的商店是什么？",
    "你会开车吗？",
    "你常常开车吗？",
    "你喜欢参加志愿活动吗？",
    "你认为志愿活动重要吗？",
    "你会讲笑话吗？",
    "你认为幽默重要吗？",
    "你喜欢看电影吗？",
    "你会写日记吗？",
    "你喜欢拍照吗？",
    "你最喜欢的季节是什么？",
    "你喜欢在家里做什么？",
    "你喜欢逛公园吗？",
    "你最喜欢的节日是什么？",
    "你在家里有几个房间？",
    "你喜欢你的工作吗？",
    "你觉得上班难吗？",
    "你对什么感兴趣？",
]

chinese_a2_possible_answers = [
    "how was your day today",
    "what do you usually do on weekends",
    "do you often go to the cinema",
    "what is your favorite movie",
    "what are your plans for tomorrow",
    "do you like reading",
    "what is your favorite book",
    "what languages can you speak",
    "where do you work",
    "do you have work experience",
    "do you like cooking",
    "what is your favorite food",
    "have you ever been abroad",
    "what is the most interesting city you have visited",
    "what do you think of chinese",
    "do you listen to music",
    "what type of music do you like",
    "what are your hobbies",
    "what sports do you do",
    "what is your favorite sport",
    "do you like to travel",
    "where do you want to travel to",
    "when is your birthday",
    "do you celebrate the new year",
    "what do you eat on your birthday",
    "can you ride a bike",
    "do you prefer mountains or the sea",
    "what is your favorite drink",
    "do you drink coffee or tea",
    "how often do you go to a restaurant",
    "have you played chess games",
    "what is your favorite board game",
    "do you have pets",
    "what is your pet's name",
    "do you like to attend parties",
    "do you often hang out with friends",
    "can you dance",
    "have you ever participated in any competitions",
    "do you think exercise is important",
    "what type of activities do you like to participate in",
    "what are your plans for the future",
    "what new skills do you want to learn",
    "which sport do you think is the most interesting",
    "do you like to surf the internet",
    "do you often use social media",
    "have you watched any TV dramas",
    "which drama do you like",
    "can you play any musical instruments",
    "which instrument do you want to learn",
    "do you like watching live streams",
    "what do you think is a healthy diet",
    "do you think rest is important",
    "what do you like to do on weekends",
    "are you interested in environmental protection",
    "do you like gardening",
    "do you often go shopping",
    "what do you like to buy",
    "what is your favorite store",
    "can you drive",
    "do you drive often",
    "do you like to participate in volunteer activities",
    "do you think volunteering is important",
    "can you tell jokes",
    "do you think humor is important",
    "do you like watching movies",
    "do you keep a diary",
    "do you like taking photos",
    "what is your favorite season",
    "what do you like to do at home",
    "do you like to walk in the park",
    "what is your favorite holiday",
    "how many rooms do you have in your house",
    "do you like your job",
    "do you think work is difficult",
    "what are you interested in",
]

chinese_b1_possible_questions = [
    "你对未来有什么计划？",
    "你认为什么是成功？",
    "你喜欢哪种类型的电影？",
    "你最近看过什么书？",
    "你喜欢户外活动吗？",
    "你对健康饮食有什么看法？",
    "你觉得怎样才能保持良好的身体健康？",
    "你觉得上大学重要吗？",
    "你喜欢和朋友一起旅行吗？",
    "你曾经参加过什么活动吗？",
    "你对你的职业有什么期望？",
    "你认为如何才能平衡工作和生活？",
    "你喜欢做志愿者吗？",
    "你对学习新技能有什么建议？",
    "你认为哪种音乐最能表达情感？",
    "你喜欢和家人一起做什么？",
    "你认为什么是幸福？",
    "你有怎样的朋友？",
    "你如何处理压力？",
    "你会如何庆祝你的生日？",
    "你认为友谊重要吗？",
    "你有什么兴趣爱好？",
    "你在假期时通常做什么？",
    "你最喜欢的旅行目的地是哪里？",
    "你对技术有什么看法？",
    "你认为社交媒体对人际关系的影响是什么？",
    "你如何看待工作与休闲的平衡？",
    "你觉得团队合作重要吗？",
    "你会如何应对失败？",
    "你有什么人生目标？",
    "你如何看待教育的重要性？",
    "你认为旅游的好处是什么？",
    "你有没有什么值得分享的经历？",
    "你如何保持积极的心态？",
    "你认为未来的工作会有什么变化？",
    "你有什么建议给年轻人？",
    "你喜欢参加社交活动吗？",
    "你如何看待压力管理？",
    "你认为梦想能否成真？",
    "你认为怎样才能提高自己的能力？",
    "你有什么特别的才能或技能吗？",
    "你如何评估自己的人生？",
    "你认为社交技能重要吗？",
    "你会如何处理与朋友的冲突？",
    "你如何看待自我提升？",
    "你认为幸福来自哪里？",
    "你对家庭有怎样的看法？",
    "你觉得个人发展重要吗？",
    "你喜欢听什么类型的音乐？",
    "你认为什么是最好的学习方式？",
    "你最喜欢的节日是什么？",
    "你在假期有什么特别的计划？",
    "你对未来的科技有什么期望？",
    "你如何看待人生中的挑战？",
    "你有没有什么人生哲学？",
    "你如何看待友谊的变化？",
]

chinese_b1_possible_answers = [
    "what are your plans for the future",
    "what do you think is success",
    "what type of movies do you like",
    "what book have you read recently",
    "do you like outdoor activities",
    "what do you think about healthy eating",
    "how can one maintain good health",
    "do you think university is important",
    "do you like to travel with friends",
    "have you participated in any activities",
    "what are your expectations for your career",
    "how can one balance work and life",
    "do you like volunteering",
    "what advice do you have for learning new skills",
    "what kind of music best expresses emotions",
    "what do you like to do with your family",
    "what do you think happiness is",
    "what kind of friends do you have",
    "how do you handle stress",
    "how would you celebrate your birthday",
    "do you think friendship is important",
    "what are your hobbies",
    "what do you usually do on vacation",
    "what is your favorite travel destination",
    "what do you think about technology",
    "what impact do you think social media has on relationships",
    "how do you view the balance between work and leisure",
    "do you think teamwork is important",
    "how would you deal with failure",
    "what are your life goals",
    "how do you view the importance of education",
    "what benefits do you think traveling has",
    "do you have any experiences worth sharing",
    "how do you maintain a positive attitude",
    "what changes do you think will happen in future jobs",
    "what advice would you give to young people",
    "do you enjoy social activities",
    "how do you view stress management",
    "do you think dreams can come true",
    "how can one improve their skills",
    "do you have any special talents or skills",
    "how do you evaluate your life",
    "do you think social skills are important",
    "how would you handle conflicts with friends",
    "how do you view self-improvement",
    "where do you think happiness comes from",
    "what is your view on family",
    "do you think personal development is important",
    "what type of music do you like to listen to",
    "what do you think is the best way to learn",
    "what is your favorite holiday",
    "do you have any special plans for the holidays",
    "what are your expectations for future technology",
    "how do you view the challenges in life",
    "do you have any life philosophies",
    "how do you see the changes in friendship",
]
